{% set name = "finance_enums" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 501ca8382ba7a147ef6644dbf22882093f71ac524bc93a4b0420d82b16d22e94

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: finance_enums
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('rust') }}
      host:
        - python
        - pip
        - maturin >=1,<2
      run:
        - python

    test:
      imports:
        - finance_enums
      commands:
        - pip check
      requires:
        - pip

  - name: finance-enums
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("finance_enums", exact=True) }}

    test:
      imports:
        - finance_enums

about:
  home: https://github.com/timkpaine/finance_enums
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Standard Financial Enumerations
  dev_url: https://github.com/timkpaine/superstore

extra:
  recipe-maintainers:
    - timkpaine
