{% set name = "finance_enums" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f95a947bd66e07375c2e27d845f4803734705b7205c343edcf3d3fc0c96c7845
  patches:
    - patches/0001-Fixes-for-conda-build.patch

build:
  number: 0
  script:
    - set CMAKE_GENERATOR=Visual Studio 17 2022  # [win]
    - {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: finance_enums
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja
        - scikit-build
      host:
        - python
        - pip
        - numpy
        - pybind11
        - scikit-build
      run:
        - python

    test:
      imports:
        - finance_enums
      commands:
        - pip check
      requires:
        - pip

  - name: finance-enums
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("finance_enums", exact=True) }}

    test:
      imports:
        - finance_enums

about:
  home: https://github.com/timkpaine/finance_enums
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Standard Financial Enumerations
  dev_url: https://github.com/timkpaine/superstore

extra:
  recipe-maintainers:
    - timkpaine
