context:
  name: finance_enums
  version: "0.7.0"
  build: 0

recipe:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 9748e6df1b9f00527dd1fb63b80bb4d924278719fa7ee95eae83b4780c438f6e

build:
  number: ${{ build }}

outputs:
  - package:
      name: finance_enums
    build:
      number: ${{ build }}
      python:
        version_independent: true
      script:
        - if: unix
          then: export PYO3_PYTHON="$PYTHON"
          else: set "PYO3_PYTHON=%PYTHON%"
        - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      skip: is_abi3 and not is_python_min

    requirements:
      build:
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
            - crossenv
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('rust') }}
        - cargo-bundle-licenses
      host:
        - python
        - pip
        - hatchling
        - hatch-rs >=0.2.0
        - if: is_abi3
          then:
            - python-abi3
      run:
        - python >=${{ python_min }}

    tests:
      - python:
          imports:
            - finance_enums
          pip_check: true
          python_version: 
            - ${{ python_min }}.*
            - "*"
      - requirements:
          run:
            - abi3audit
        script:
          - if: unix
            then: abi3audit $SP_DIR/finance_enums/_finance_enums.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
            else: abi3audit %SP_DIR%/finance_enums/_finance_enums.pyd -s -v --assume-minimum-abi3 ${{ python_min }}

  - package:
      name: finance-enums
    build:
      noarch: generic
      number: ${{ build }}
      skip:
        - not target_platform == "linux-64"
    requirements:
      run:
        - ${{ pin_subpackage('finance_enums', upper_bound='x.x.x', lower_bound='x.x.x') }}
    about:
      license_file: []
    tests:
      - python:
          imports:
            - finance_enums
          pip_check: true
          python_version: 
            - ${{ python_min }}.*
            - "*"
      - requirements:
          run:
            - abi3audit
        script:
          - if: unix
            then: abi3audit $SP_DIR/finance_enums/_finance_enums.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
            else: abi3audit %SP_DIR%/finance_enums/_finance_enums.pyd -s -v --assume-minimum-abi3 ${{ python_min }}

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Standard Financial Enumerations
  homepage: https://github.com/prettygoodcapital/finance_enums
  repository: https://github.com/prettygoodcapital/finance_enums

extra:
  recipe-maintainers:
    - pgc-dev
